export type Chapter = {
  number: number;
  slug: string;
  title: string;
  dependencies: string;
  commands: readonly string[];
  template: string;
};

export const CHAPTERS: readonly Chapter[] = [
  {
    number: 1,
    slug: "introduction-and-goals",
    title: "Introduction and Goals",
    dependencies: "Start here; quality-goal IDs are used by chapters 4, 5, and 9",
    commands: ["arc42 explain quality-goal", "arc42 explain quality-scenario"],
    template:
      "# Introduction and Goals\n\n<!--\nArc42 chapter 1. Describes the relevant requirements and the driving forces that\narchitects and the development team must consider.\n\nThis chapter has three subsections:\n\n1.1 Requirements Overview\n  Short description of the functional requirements and business goals \u2014 not a full\n  requirements spec. Write a compact summary or refer to an external requirements\n  document. A brief prose paragraph and/or a table of the most important use cases.\n\n1.2 Quality Goals\n  The top three to five quality goals for the architecture (highest-importance only).\n  Write a single sentence or short paragraph, then link to chapter 10.\n  Do NOT repeat the quality-goal blocks here \u2014 they live in 10-quality-requirements.arc42.md.\n\n  Example:\n\n  See [10-quality-requirements.arc42.md](10-quality-requirements.arc42.md) for the\n  complete quality catalog with priorities and measurable scenarios.\n\n1.3 Stakeholders\n  A table of all stakeholders: their role, contact, and expectations from the\n  architecture and its documentation. Think broadly \u2014 include teams that must\n  maintain the system, operators, auditors, and external partners.\n\nSee https://docs.arc42.org/section-1/ for further guidance.\n\nExample:\n\n## 1.1 Requirements Overview\n\nThe system provides an online bookstore backend with catalog search, order placement,\nand customer account management. The key business goal is to maximise conversion by\nkeeping search fast and the checkout flow frictionless.\n\n## 1.2 Quality Goals\n\nSee 10-quality-requirements.arc42.md for the full catalog with measurable scenarios.\n\n## 1.3 Stakeholders\n\n| Role              | Contact       | Expectations                                            |\n|-------------------|---------------|---------------------------------------------------------|\n| Product Owner     | \u2026             | Functional coverage, no surprises in scope              |\n| Lead Developer    | \u2026             | Clear component boundaries, up-to-date decision records |\n| Security Officer  | \u2026             | Documented auth and encryption decisions                |\n| CI Pipeline       | \u2014             | Stable JSON output, reliable exit codes                 |\n-->\n\n## 1.1 Requirements Overview\n\n## 1.2 Quality Goals\n\nSee [10-quality-requirements.arc42.md](10-quality-requirements.arc42.md) for the complete\nquality catalog with priorities and measurable scenarios.\n\n## 1.3 Stakeholders\n",
  },
  {
    number: 2,
    slug: "constraints",
    title: "Architecture Constraints",
    dependencies: "Do early; constraint IDs are used by strategy and decisions",
    commands: ["arc42 explain constraint"],
    template:
      "# Architecture Constraints\n\n<!--\nArc42 chapter 2. Document every requirement that limits your freedom of design and\nimplementation decisions. Constraints must always be dealt with \u2014 though some may be\nnegotiable. Architects need to know exactly where they have freedom and where they must adhere.\n\nConstraints come from three sources:\n- technical       \u2014 technology standards, infrastructure mandates, platform restrictions\n- organizational  \u2014 legal requirements, compliance rules, budget limits, governance policies\n- convention      \u2014 agreed coding standards, naming rules, documentation or versioning guidelines\n\nFor each constraint, write a ## section with a prose paragraph explaining the constraint,\nits origin, and its architectural impact, followed by a DSL block.\n\nThe `source` field names the origin \u2014 a legal document, client contract, governance policy,\nor internal standard. Omit it if the origin is an internal assumption.\n\nSee https://docs.arc42.org/section-2/ for further guidance.\n\nExample:\n\n## Personal Data Must Remain in the EU\n\nAll personally identifiable information must be stored and processed within the EU.\nThis limits which cloud regions, caching layers, and third-party SaaS tools are usable.\nOrigin: GDPR Art. 44, confirmed by legal review 2025-03-01.\n\n```arc42\n:::constraint\nid: con-data-residency\ntitle: Personal Data Must Remain in the EU\ncategory: organizational\nsource: GDPR Art. 44 / Legal review 2025-03-01\n:::\n```\n-->\n",
  },
  {
    number: 3,
    slug: "system-context",
    title: "System Scope and Context",
    dependencies:
      "Establishes actors and actor requirements for the building-block and runtime views.",
    commands: ["arc42 explain actor"],
    template:
      "# System Scope and Context\n\n<!--\nArc42 chapter 3. Define the boundary of your system and name every external party that\ninteracts with it. \"External\" means anything outside your system boundary \u2014 people, roles,\norganisations, or other software systems that send or receive data, trigger behaviour, or\ndepend on your system's results.\n\nTwo types of actors:\n- person  \u2014 a human role: end user, administrator, operator, support team, auditor\n- system  \u2014 an external software system or service: third-party API, legacy system,\n            message broker, external database, partner service\n\nFor each actor, write a ## section with a prose paragraph explaining who or what the\nexternal party is and why it matters to the system, followed by an actor block with a\n`requires` field listing the interface IDs it depends on.\n\nThen add a context diagram containing the actors and only those building blocks that provide an\ninterface directly required by an actor. Internal-only providers belong in chapter 5. Actors\nreference the interface IDs they require; interface definitions belong beneath their provider\nbuilding blocks in chapter 5.\n\nSee https://docs.arc42.org/section-3/ for further guidance.\n\nExample:\n\n## End User\n\nThe primary human user of the system. Interacts via the web UI to browse, search, and\npurchase products. Authentication is handled by the system itself \u2014 no external identity\nprovider in scope for v1.\n\n```arc42\n:::actor\nid: actor-end-user\ntitle: End User\ntype: person\ndescription: Authenticated customer browsing and purchasing via the web UI\nrequires: if-user-checkout\n:::\n```\n\n## Payment Provider\n\nAn external payment processing service (e.g. Stripe). The system calls its REST API\nto authorise charges and process refunds. No payment data is stored in the system itself.\n\n```arc42\n:::actor\nid: actor-payment-provider\ntitle: Payment Provider\ntype: system\nrequires: if-checkout-payment\n:::\n```\n\nKeep this chapter's actor blocks focused on the interfaces they require and use the context diagram\nfor actor-facing building blocks only. Do not define interface blocks in chapter 3.\n-->\n",
  },
  {
    number: 4,
    slug: "solution-strategy",
    title: "Solution Strategy",
    dependencies: "Depends on goals and constraints.",
    commands: ["arc42 explain solution-strategy"],
    template:
      "# Solution Strategy\n\n<!--\nArc42 chapter 4 describes one coherent solution strategy for the whole architecture.\nUnlike chapters that contain one element per subsection, this chapter has at most one\nsolution-strategy block. Keep the detailed explanation in the Markdown prose below and\ndo not create one block for each subsection.\n\nStart with a short overview before the block. Link the strategy to the quality goals it\naddresses; use comma-separated quality-goal ids. The referenced goals are defined in\n01-quality-goals.arc42.md.\n\n```arc42\n:::solution-strategy\nid: strategy-architecture\ntitle: Architecture-wide solution strategy\naddresses: qg-performance, qg-security\n:::\n```\n\n## System decomposition\n\nExplain the fundamental decomposition and how it supports the quality goals.\n\n## Technology and communication approach\n\nExplain the main technology, deployment, and communication choices.\n\n## Operational approach\n\nExplain the cross-cutting operational principles that shape the solution.\n\nSee https://docs.arc42.org/section-4/ for further guidance.\n-->\n",
  },
  {
    number: 5,
    slug: "building-blocks",
    title: "Building Blocks",
    dependencies: "Create stable building-block IDs before dependent chapters add references.",
    commands: ["arc42 explain building-block", "arc42 explain interface"],
    template:
      "# Building Blocks\n\n<!--\nArc42 chapter 5. Document the system's static decomposition into building blocks and their\ninterfaces. This view is mandatory for every architecture documentation \u2014 it is the floor plan\nof your system.\n\nA building block is any deployable or logically cohesive unit: a service, module, subsystem,\nlibrary, layer, or component. Start with the most important top-level blocks. Refine individual\nblocks into sub-blocks (using the `parent` field) only when the internal structure is\narchitecturally significant.\n\nAn interface is a provider-owned contract used by one or more actors or building blocks.\nEvery significant communication path should have an interface.\nThe `provider` field identifies the building block that provides the interface.\nConsumers declare which interfaces they require in their `requires` list.\n\nFor each building block, write a ## section with a prose paragraph explaining purpose, responsibility,\nand key constraints, followed by a DSL block. Define each provided interface as a direct subheading\nof its provider building block. Use a provider-oriented heading and put interface consumption on the\nconsumer building block's `requires` list.\n\nPrefer relevance over completeness \u2014 document what is surprising, risky, or complex.\nLeave out boring, standardised, or self-explanatory parts.\n\nSee https://docs.arc42.org/section-5/ for further guidance.\n\nExample:\n\n## API Gateway\n\nThe single entry point for all external traffic. Authenticates requests, applies rate limits,\nand routes calls to downstream services. External clients never contact services directly.\n\n```arc42\n:::building-block\nid: bb-api-gateway\ntitle: API Gateway\ntechnology: nginx / Kong\nimplements: concept-auth, concept-logging\n:::\n```\n\n## User Service\n\nOwns user identity and authentication. Issues tokens on successful login.\n\n```arc42\n:::building-block\nid: bb-user-service\ntitle: User Service\ntechnology: Java / Spring Boot\nimplements: concept-auth, concept-logging\n:::\n```\n\n### User Service Interface\n\nThe API Gateway forwards authentication requests to the User Service.\nThis is the only path through which external login requests reach the User Service.\n\n```arc42\n:::interface\nid: if-gateway-user\ntitle: User Service Interface\nprovider: bb-user-service\nprotocol: HTTP/REST\n:::\n```\n-->\n",
  },
  {
    number: 6,
    slug: "runtime-view",
    title: "Runtime View",
    dependencies: "Depends on actors, building blocks, and interfaces.",
    commands: ["arc42 explain interface", "arc42 explain actor"],
    template:
      "# Runtime View\n\n<!--\nArc42 chapter 6. Document a representative selection of architecturally relevant runtime flows:\nimportant use cases, external interactions, startup/shutdown, administration, and error paths.\nPrefer prose-first sections. Explain the trigger, responsibilities, notable interactions, and\nsuccess or failure behavior before adding the structured scenario summary.\n\nThe `involves` field contains comma-separated building-block IDs. It is optional in the model, but\nscenarios without it receive warning W011. Interfaces covered by no scenario receive hint H011.\n\nExample:\n\n## Customer checkout\n\nThe customer submits an order. The API validates it, the order service creates the order, and the\npayment service authorizes payment before the customer receives confirmation.\n\n```arc42\n:::runtime-scenario\nid: scenario-checkout\ntitle: Customer checkout\ntrigger: Customer submits an order\ninvolves: bb-api, bb-order-service, bb-payment-service\n:::\n```\n\nMermaid sequence diagrams may be attached using the project's explicit diagram association syntax.\nUse model IDs (or explicit safe aliases) for participants and labels only for display:\n\n```arc42\n:::diagram\nid: checkout-sequence\nscenario: scenario-checkout\nnotation: mermaid-sequence\n:::\n```\n\n```mermaid\nsequenceDiagram\n    actor customer as Customer\n    participant bb_api as API Gateway\n    participant bb_order_service as Order Service\n    customer->>bb_api: Submit order\n    bb_api->>bb_order_service: Create order\n```\n\nState diagrams remain ordinary Markdown artifacts and are not parsed or linted by this feature.\n-->\n",
  },
  {
    number: 7,
    slug: "deployment-view",
    title: "Deployment View",
    dependencies: "Depends on building-block IDs and deployment evidence.",
    commands: ["arc42 explain deployment-node"],
    template:
      "# Deployment View\n\n<!--\nArc42 chapter 7. Describe the infrastructure relevant to the software architecture: environments,\nregions, servers, containers, devices, operational boundaries, and the relationships between them.\nExplain why the selected deployment topology matters, including important characteristics and\noperational prerequisites.\n\nRecommended structure:\n1. Open with a deployment overview section that contains the whole-model diagram \u2014 readers need\n   the big picture before the per-node detail. Use a `:::diagram` block with `view: deployment`\n   and `notation: mermaid-architecture` immediately below the introductory prose.\n2. Follow with one `##` section per deployment environment or significant infrastructure node.\n   Each section ends with a `:::deployment-node` block as the machine-readable summary.\n3. Optionally add scoped diagrams (with `roots:`) for important subsystems.\n\n`type` is optional and must be one of `server`, `container`, `device`, `cloud-region`, or\n`environment`. `hosts` contains comma-separated building-block IDs. `parent` creates a hierarchy\nbetween deployment nodes. Multiple nodes may host the same building-block, and composite\nbuilding-blocks do not need a direct host mapping.\n\nDiagrams are optional named views over the structured nodes and do not create additional model\nelements. Omit `roots` for a whole-model overview, or supply deployment-node IDs to scope the\ndiagram to a subtree. Use explicit `safe-id=model-id` aliases only when a model ID is not a valid\nMermaid identifier.\n\nExample:\n\n## Deployment overview\n\nThere are two environments: production and staging. Production is the primary target; staging\nmirrors it for pre-release validation.\n\n```arc42\n:::diagram\nid: my-system-deployment\nview: deployment\nnotation: mermaid-architecture\n:::\n```\n\n```mermaid\narchitecture-beta\n    group env-prod(cloud)[Production]\n    service bb-api(server)[API] in env-prod\n    service bb-database(database)[Database] in env-prod\n    bb-api:R --> L:bb-database\n\n````\n\n## Production\n\nThe production environment runs in the primary cloud region. The API and database are co-located\nin the same region for low-latency access.\n\n```arc42\n:::deployment-node\nid: env-production\ntitle: Production\ntype: environment\nhosts: bb-api, bb-database\n:::\n````\n\n## Staging\n\nMirrors the production topology for pre-release validation. Uses smaller instance sizes.\n\n```arc42\n:::deployment-node\nid: env-staging\ntitle: Staging\ntype: environment\nhosts: bb-api, bb-database\n:::\n```\n\n-->\n",
  },
  {
    number: 8,
    slug: "concepts",
    title: "Cross-cutting Concepts",
    dependencies: "Define concept IDs before linking building blocks with implements.",
    commands: ["arc42 explain concept"],
    template:
      "# Cross-cutting Concepts\n\n<!--\nArc42 chapter 8. Document the cross-cutting concerns, patterns, and principles that apply\nconsistently across multiple building blocks. Concepts form the basis for conceptual integrity \u2014\nthe consistency and homogeneity of your architecture.\n\nA concept is anything that cuts across component boundaries: security patterns, error handling\nstrategies, logging conventions, persistence approaches, messaging patterns, deployment\nconventions, testing strategies, and so on.\n\nDo not attempt to cover every possible topic. Pick only the concepts that are architecturally\nsignificant for your system \u2014 those that building blocks must implement consistently, and where\na central description is more useful than repeating the same text in each building block.\n\nFor each concept, write a ## section with a prose paragraph describing the concept, the\ndecision behind it, and its implications for the building blocks that must implement it,\nfollowed by a DSL block.\n\nBuilding blocks reference concepts via the `implements` field in chapter 5, making coverage\nexplicit and verifiable.\n\nSee https://docs.arc42.org/section-8/ for further guidance.\n\nExample:\n\n## Structured Logging\n\nEvery service emits structured JSON log entries including traceId, service, duration,\noutcome, and timestamp. The traceId is propagated via the X-Trace-Id HTTP header\nand copied to all outbound calls and log entries.\n\n```arc42\n:::concept\nid: concept-logging\ntitle: Structured Logging\ncategory: observability\n:::\n```\n-->\n",
  },
  {
    number: 9,
    slug: "decisions",
    title: "Architecture Decisions",
    dependencies: "Depends on goals, constraints, risks, and strategy IDs.",
    commands: ["arc42 explain decision"],
    template:
      "# Architecture Decisions\n\n<!--\nArc42 chapter 9. Document the significant architecture decisions as Architecture Decision\nRecords (ADRs). Capture any choice that was expensive, risky, or that future maintainers\nwill wonder about.\n\nAvoid redundancy with section 4 (solution strategy) \u2014 refer to it for the highest-level\nchoices and use this chapter for detail and rationale.\n\nFor each decision, write a ## section with a prose paragraph explaining the context,\nthe alternatives considered, and the rationale for the chosen option, followed by a DSL block.\nDocument rejected alternatives so future readers understand what was considered.\n\nStatus values:\n  proposed   \u2014 under discussion, not yet in force\n  accepted   \u2014 in force\n  deprecated \u2014 no longer recommended but not yet replaced\n  superseded \u2014 replaced by another decision\n\nWhen a new decision replaces an old one, set status: superseded on the old decision\nand add supersedes: <old-id> on the new decision.\n\nThe `date` field should be ISO 8601 (YYYY-MM-DD).\nThe `addresses` field links to quality goals and constraints this decision responds to.\n\nSee https://docs.arc42.org/section-9/ for further guidance.\n\nExample:\n\n## Stateless Token Authentication\n\nThe team evaluated session-based (server-side store) and token-based (stateless) authentication.\nStateless tokens were chosen to avoid a shared session store that would introduce a single point\nof failure and complicate horizontal scaling.\n\n```arc42\n:::decision\nid: dec-auth-stateless\ntitle: Stateless Token Authentication\nstatus: accepted\ndate: 2025-07-01\naddresses: qg-security, qg-performance\n:::\n```\n\nTo supersede a decision, mark the old one and point to it from the new one:\n\n```arc42\n:::decision\nid: dec-auth-old\ntitle: Session-based Authentication\nstatus: superseded\ndate: 2024-01-15\n:::\n```\n\n```arc42\n:::decision\nid: dec-auth-new\ntitle: OAuth2 Token Authentication\nstatus: accepted\ndate: 2025-09-01\nsupersedes: dec-auth-old\n:::\n```\n-->\n",
  },
  {
    number: 10,
    slug: "quality-requirements",
    title: "Quality Requirements",
    dependencies: "Elaborates the quality goals from chapter 1.",
    commands: ["arc42 explain quality-scenario"],
    template:
      "# Quality Requirements\n\n<!--\nArc42 chapter 10. This chapter documents all quality requirements in two parts:\n\n10.1 Quality Goals\n  Capture the top three to five high-priority quality goals that drive the architecture.\n  Quality goals are non-functional requirements whose fulfilment is of highest importance\n  to your major stakeholders. They are not project goals \u2014 they describe properties the\n  running system must exhibit.\n\n  Focus on what matters most: if you had to choose between conflicting requirements, these\n  goals tell you which wins. Base them on ISO 25010 characteristics: performance efficiency,\n  reliability, security, maintainability, usability, portability, compatibility.\n\n  Priority values:\n    high   \u2014 architecture-driving; must be satisfied; drives the solution strategy\n    medium \u2014 important; should be addressed by decisions or concepts\n    low    \u2014 desirable; influences design choices but not a hard constraint\n\n10.2 Quality Scenarios\n  Make each quality goal concrete and testable through one or more scenarios.\n  A scenario names a source, a stimulus, the environment, the system response, and a\n  measurable metric. Without a metric the scenario is aspirational but not useful for\n  architecture evaluation (ATAM) or acceptance testing.\n\n  The `quality` field references the quality-goal id this scenario elaborates.\n\nSee https://docs.arc42.org/section-10/ for further guidance.\n\nExample:\n\n## Performance\n\nThe system must handle peak load without degrading the user experience.\nResponse time directly affects user retention and is a contractual obligation\nwith our enterprise customers.\n\n```arc42\n:::quality-goal\nid: qg-performance\ntitle: Performance\npriority: high\n:::\n```\n\n## Performance \u2014 Peak Load Scenario\n\nUnder peak load the system must respond within the agreed p95 threshold.\nThis scenario is the primary test case for the performance quality goal.\n\n```arc42\n:::quality-scenario\nid: qs-perf-peak\ntitle: Peak Load Response Time\nquality: qg-performance\nstimulus: 1000 concurrent users submit requests simultaneously\nresponse: All requests are handled without error\nmetric: p95 response time stays below 500ms\n:::\n```\n-->\n\n## 10.1 Quality Goals\n\n## 10.2 Quality Scenarios\n",
  },
  {
    number: 11,
    slug: "risks",
    title: "Risks and Technical Debt",
    dependencies: "Risks may be referenced by architecture decisions.",
    commands: ["arc42 explain risk"],
    template:
      '# Risks and Technical Debt\n\n<!--\nArc42 chapter 11. Document known risks and areas of technical debt ordered by priority.\nRisk management is about making technical risks visible to the people who need to act on them.\n\nA risk is a known threat whose severity has not yet been fully mitigated.\nTechnical debt is a shortcut taken consciously or accidentally whose cost will have to be\npaid later. Both belong here.\n\nFor each risk or debt item, write a ## section with a prose paragraph describing the risk,\nits cause, its potential impact, and the current situation, followed by a DSL block.\n\nThe `mitigation` field describes the planned or accepted response. Even "accepted without\naction until X" is a valid mitigation \u2014 it shows the team made a conscious choice.\n\nOrder entries by priority \u2014 highest risk first.\n\nSee https://docs.arc42.org/section-11/ for further guidance.\n\nExample:\n\n## No Automated Performance Regression Tests\n\nThe performance quality goal has no automated gate in CI. Performance regressions can be\nintroduced without detection until a production incident occurs.\n\n```arc42\n:::risk\nid: risk-no-perf-tests\ntitle: No Automated Performance Regression Tests\nseverity: high\nmitigation: Add k6 load test suite as a nightly CI job with a p95 threshold gate.\n:::\n```\n-->\n',
  },
  {
    number: 12,
    slug: "glossary",
    title: "Glossary",
    dependencies: "Independent; complete alongside the other chapters.",
    commands: ["arc42 explain glossary-term"],
    template:
      "# Glossary\n\n<!--\nArc42 chapter 12. Define the domain and technical terms used in the architecture documentation.\nA shared glossary reduces misunderstanding by ensuring all stakeholders use the same language.\nIf you work in multi-language teams, it also serves as a translation reference.\n\nFor each term, write a ## section with a prose paragraph providing context, etymology, or\nextended explanation where useful, followed by a DSL block with a concise definition.\n\nKeep the `definition` field to one or two sentences that unambiguously identify the concept.\nExtended explanation belongs in the prose above the block.\n\nIf a short form is important, include it in the prose; the typed glossary block has no\n`abbreviation` field.\n\nNote synonyms the team has agreed NOT to use, and why, in the prose paragraph.\n\nSee https://docs.arc42.org/section-12/ for further guidance.\n\nExample:\n\n## Bounded Context\n\nA bounded context is a logical boundary within which a domain model is consistent and\nunambiguous. Inside a bounded context, terms have precise, agreed meanings. The same word\nmay mean something different in another bounded context.\n\n```arc42\n:::glossary-term\nid: term-bounded-context\ntitle: Bounded Context\ndefinition: A logical boundary within which a domain model, its language, and its rules are internally consistent. Defined in Domain-Driven Design (Evans, 2003).\n:::\n```\n-->\n",
  },
];

export function filename(chapter: Chapter): string {
  return `${String(chapter.number).padStart(2, "0")}-${chapter.slug}.arc42.md`;
}

export function chapter(number: number): Chapter | undefined {
  return CHAPTERS.find((item) => item.number === number);
}
